image:
  file: .gitpod.Dockerfile

tasks:
   - name: androidstudio
     command: |
      $HOME/android-studio/bin/studio.sh

ports:
  - port: 5900
    onOpen: ignore
    # vnc
  - port: 6080
    onOpen: open-preview
